Genesis
bluemarblepayroll/db_fuel pull request #1
Opened 2020-11-15 20:47 UTC by mattruggio

2020-11-16 22:10 UTC, gerryster commented on CHANGELOG.md
> +# 1.0.0 (TBD)
I would make this a sub 1.0 release since it sounds like the plan is to add some write centric jobs in the near future.

2020-11-16 22:48 UTC, mattruggio commented on CHANGELOG.md
> +# 1.0.0 (TBD)
If you are OK with this being 1.0.0 then let's stick with that, since 1.0.0-alpha was already published.  Moving forward, let's try and shoot for less eager major version bumps and utilize sub 1 majors for at least the first few publications/extensions.

2020-11-17 17:24 UTC, gerryster requested changes
Overall this looks good. Just some minor suggestions.

2020-11-17 17:24 UTC, gerryster commented on spec/db_fuel/library/dbee/range_spec.rb
> +      { 'fname' => 'Bozo' },
Is there a reason that this record has a string key?

2020-11-17 17:24 UTC, gerryster commented on lib/db_fuel/library/dbee/range.rb
> +      # This Burner Job does the same data query and loading as the Query Job with the addition
Could you add some more detail about what each constructor parameter does? For example, I would want to know how "key" differs from "key_path". I was able to figure this out based on the code and tests but I think a little more documentation here could help someone get up to speed.

2020-11-17 19:38 UTC, mattruggio commented on spec/db_fuel/library/dbee/range_spec.rb
> +      { 'fname' => 'Bozo' },
Just to implicitly illustrate type-indifference for keys.  I will mention this more formally within the comments.

2020-11-18 15:45 UTC, gerryster approved these changes

2020-11-18 15:47 UTC, merged