Basic ActiveRecord-specific Jobs
bluemarblepayroll/db_fuel pull request #2
Opened 2020-11-25 17:36 UTC by mattruggio

2020-11-30 15:52 UTC, gerryster commented on README.md
> +* **db_fuel/active_record/find_or_insert** [table_name, attributes, debug, primary_key, register, separator, timestamps, unique_attributes]: An extension of the `db_fuel/active_record/insert` job tha
Nitpick: sql -> SQL

2020-11-30 19:55 UTC, gerryster commented on lib/db_fuel/library/active_record/find_or_insert.rb
> +        #                pipeline, in case the data calls for sql-specific transformers
sql -> SQL

2020-11-30 20:19 UTC, gerryster commented on lib/db_fuel/library/active_record/find_or_insert.rb
> +          first_record = db_provider.first(unique_row)
Feel free to defer this as it is a performance improvement idea but it would save some IO overhead to just select the primary key column(s) instead of the entire record to check for existence. ActiveRecord's `exists?` method does something similar and selects a minimal amount of data:

```
irb(main):293:0> MyModel.exists?(42)
  MyModel Exists (0.4ms)  SELECT  1 AS one FROM `my_model` WHERE `my_model`.`id` = 42 LIMIT 1
true
```

2020-11-30 20:58 UTC, gerryster requested changes
This looks nice and clean. My biggest feedback is about support for composite primary keys.

2020-11-30 20:58 UTC, gerryster commented on lib/db_fuel/library/active_record/insert.rb
> +        #   primary_key: If primary_key is present then it will be used to set the object's
What about a table which has a primary key over multiple columns? Can primary_key be an array of those columns?

2020-11-30 20:58 UTC, gerryster commented on lib/db_fuel/library/active_record/update.rb
> +        #                pipeline, in case the data calls for sql-specific transformers
sql -> SQL

2020-11-30 20:58 UTC, gerryster commented on lib/db_fuel/modeling/keyed_column.rb
> +    # Connects a hash key to a sql column.  By default if a column is not given then its
sql -> SQL

2020-11-30 20:58 UTC, gerryster commented on lib/db_fuel/modeling/keyed_column.rb
> +    # to sql and sql to objects.
sql -> SQL

2020-12-01 03:38 UTC, mattruggio commented on lib/db_fuel/library/active_record/find_or_insert.rb
> +          first_record = db_provider.first(unique_row)
This is a good idea, let's defer this and include it in a subsequent performance optimization iteration.

2020-12-01 03:41 UTC, mattruggio commented on lib/db_fuel/library/active_record/insert.rb
> +        #   primary_key: If primary_key is present then it will be used to set the object's
Currently it only works with non-composite primary keys.  This is definitely a limitation, but no use-case is currently present that warrants this.  I would rather defer this complexity until we have time to read through more of the Arel/InsertManager/ActiveRecord API's to ensure we understand how they handle composite primary keys.

2020-12-01 03:41 UTC, mattruggio commented on lib/db_fuel/library/active_record/insert.rb
> +        #   primary_key: If primary_key is present then it will be used to set the object's
I will add a note in the README and comments for this.

2020-12-01 03:48 UTC, mattruggio commented
@gerryster - OK, I made the necessary documentation changes but would like to defer the composite primary key and performance optimizations as future enhancements.  I would prefer to not defer these, but due to time constraints and lack of real world feedback/use cases leads me to believe we should tackle these later.  Let me know if you agree with this assessment.

2020-12-01 22:45 UTC, gerryster approved these changes
I agree with deferring composite primary keys.

2020-12-01 23:41 UTC, merged