Upsert
bluemarblepayroll/db_fuel pull request #5
Opened 2021-01-13 19:41 UTC by johnbos

2021-03-04 17:29 UTC, gerryster requested changes
Looks good overall, just some minor feedback inline.

2021-03-08 19:59 UTC, johnbos commented on README.md
> +* **db_fuel/active_record/update** [name, table_name, attributes, debug, register, primary_key, separator, timestamps, unique_attributes]: This job can take the unique objects in a register and updat
Renamed primary_key to primary_keyed_column. Updated references in README.md, also updated note regarding composite primary keys for the update method.

2021-03-08 19:59 UTC, johnbos commented on lib/db_fuel/modeling/attribute_renderer_set.rb
> +      def initialize(attributes: [], resolver: nil)
Re-ordered parameters and removed default value for resolver.

2021-03-08 20:37 UTC, johnbos commented on lib/db_fuel/modeling/attribute_renderer_set.rb
> +    class AttributeRendererSet
Added # :nodoc:

2021-03-08 20:37 UTC, johnbos commented on lib/db_fuel/modeling/attribute_renderer_set.rb
> +      def make_attribute_renderers(attributes)
Renamed make_attribute_renderers to make_renderers.

2021-03-08 20:37 UTC, johnbos commented on lib/db_fuel/modeling/attribute_renderer_set.rb
> +      def created_at_timestamp_attribute
Updated constants for CREATED_AT and UPDATED_AT. Removed timestamp_attribute method.

2021-03-08 20:38 UTC, johnbos commented on lib/db_fuel/version.rb
> +  VERSION = '1.2.1-alpha.3'
Updated version to 2.0.0.

2021-03-09 22:06 UTC, gerryster approved these changes
LGTM. Note that the created_at_timestamp_attribute and similar updated_at methods can be removed and the constants can be used in their place.

2021-03-16 17:29 UTC, merged